name: Test

on:
  push

jobs:
  main:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
      - name: Allow PowerShell to run unsigned scripts  # https://github.com/actions/runner/issues/686
        shell: cmd
        run: powershell -Command "Set-ExecutionPolicy RemoteSigned -Scope CurrentUser"
      - name: Setup Python
        uses: actions/setup-python@v5.5.0
        with:
          python-version: 3.12
      - name: Install dependencies
        shell: powershell
        run: |
          pip install -e .
      - name: Create EXE
        shell: powershell
        run: |
          python scripts/hello.py
